### ISSUE TITLE
publish message one time only

### ISSUE THREAD

**Issue by Cokthemhok** [Sashiri/ros_nodes#6]
Firstly, thank you for this awesome project.

And I have one question, can I publish ros message one time only?

**Comment by Sashiri** [comment]
Unfortunately there's no library way of publishing once.
As of now you'd need to create a publisher, stop it, and then publish it manually whenever you're ready

```dart
var config = RosConfig(
  'ros_nodes_example_node',
  'http://127.0.0.1:11311/',
  '127.0.0.1',
  24125,
);
var client = RosClient(config);
var topic = RosTopic('chatter', StdMsgsString());
var publisher = await client.register(topic);
publisher.stopPublishing();
await publisher.publishData();
await client.unregister(topic);
```

Or if you pull new change
```dart
var config = RosConfig(
  'ros_nodes_example_node',
  'http://127.0.0.1:11311/',
  '127.0.0.1',
  24125,
);
var client = RosClient(config);
var topic = RosTopic('chatter', StdMsgsString());
var publisher = await client.register(topic, startPublishing: false);
await publisher.publishData();
await client.unregister(topic);
```

The end effect would be publishing topic once and then stopping ;D
If you have any other idea how would or should it work, then let's talk about it

Also if you look for a ros library that's more similar to c++/nodejs version, checkout https://github.com/TimWhiting/dartros

**Comment by Cokthemhok** [comment]
Thank you so much.
I understood. :)
